name: Continuous Integration

on:
  pull_request:
    branches: ['**']
    types: [opened, synchronize, reopened, edited, labeled]
  push:
    branches: ['**']
    tags: [v*]

jobs:
  build:
    name: Build and Test
    strategy:
      matrix:
        os: [ubuntu-latest]
        scala: [2.12.15, 2.13.8, 3.1.2]
        java: [graal_21.1.0@11, temurin@8]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: template

      - name: Setup GraalVM (graal_21.1.0@11)
        if: matrix.java == 'graal_21.1.0@11'
        uses: DeLaGuardo/setup-graalvm@5.0
        with:
          graalvm: 21.1.0
          java: java11

      - name: Setup Java (temurin@8)
        if: matrix.java == 'temurin@8'
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 8

      - name: Cache sbt
        uses: actions/cache@v2
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.coursier/cache/v1
            ~/.cache/coursier/v1
            ~/AppData/Local/Coursier/Cache/v1
            ~/Library/Caches/Coursier/v1
          key: ${{ runner.os }}-sbt-cache-v2-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}

      - name: Install Template Locally
        run: |
          ls -al
          